### ISSUE TITLE
Typo in /setup/docker-compose.yml

### ISSUE THREAD

**Issue by dpeluso** [stefanwerfling/flyingfish#50]
Interesting project thanks for sharing. FWIW there is a typo in /setup/docker-compose.yml line 

https://github.com/stefanwerfling/flyingfish/blob/b87426f0b67c499297ef9af88198061ee2f3bea5/setup/docker-compose.yml#L50

Missing the 'y' in flyingfish
    image: stefanwerfling/flyingfish:latest

**Comment by stefanwerfling** [comment]
Oh! Thanks! I will fix it.
